# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.browsewithcaret", true);
user_pref("accessibility.typeaheadfind", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1244143445);
user_pref("app.update.lastUpdateTime.background-update-timer", 1244143440);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1244143440);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1244143446);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1244143450);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "file:///usr/share/hercules/index.html");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.10");
user_pref("extensions.lastAppVersion", "3.0.10");
user_pref("extensions.update.enabled", false);
user_pref("font.size.variable.x-western", 10);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1246735471);
